version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.*
          - push
    payload:
      maxRunTime: 3600
      image: grenade/opencloudconfig
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          ./ci/validate.sh
    metadata:
      name: validate
      description: run linters and validations against new code commits
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
    payload:
      maxRunTime: 3600
      image: hashicorp/packer:light
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          ./ci/build-ami.sh
    metadata:
      name: build-ami
      description: create a new ec2 ami from an iso image
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: public
